export * from './accountApi.service';
import { AccountApiService } from './accountApi.service';
export * from './authenticationApi.service';
import { AuthenticationApiService } from './authenticationApi.service';
export * from './banApi.service';
import { BanApiService } from './banApi.service';
export * from './characterApi.service';
import { CharacterApiService } from './characterApi.service';
export * from './factionApi.service';
import { FactionApiService } from './factionApi.service';
export * from './kickApi.service';
import { KickApiService } from './kickApi.service';
export * from './propertyApi.service';
import { PropertyApiService } from './propertyApi.service';
export * from './quizApi.service';
import { QuizApiService } from './quizApi.service';
export * from './vehicleApi.service';
import { VehicleApiService } from './vehicleApi.service';
export * from './warnApi.service';
import { WarnApiService } from './warnApi.service';
export const APIS = [AccountApiService, AuthenticationApiService, BanApiService, CharacterApiService, FactionApiService, KickApiService, PropertyApiService, QuizApiService, VehicleApiService, WarnApiService];
