/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Ban { 
    id?: number;
    account: string;
    reason: string;
    adminAccount?: string;
    ipAddress: string;
    expiringAt: string;
    createdAt: Date;
}