/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type BizType = 0 | 1 | 2 | 3 | 4 | 5;

export const BizType = {
    NUMBER_0: 0 as BizType,
    NUMBER_1: 1 as BizType,
    NUMBER_2: 2 as BizType,
    NUMBER_3: 3 as BizType,
    NUMBER_4: 4 as BizType,
    NUMBER_5: 5 as BizType
};
