/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CharacterGender = 0 | 1;

export const CharacterGender = {
    NUMBER_0: 0 as CharacterGender,
    NUMBER_1: 1 as CharacterGender
};