/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Vehicle } from './vehicle';

export interface Character { 
    id?: number;
    name: string;
    birthday: string;
    gender: Character.GenderEnum;
    health: number;
    armour: number;
    skin: number;
    money: number;
    paycheck: number;
    bank: number;
    savings: number;
    hours: number;
    minutes: number;
    level: number;
    positionX: number;
    positionY: number;
    positionZ: number;
    angle: number;
    virtualWorld: number;
    interior: number;
    vehicles?: Array<Vehicle>;
    factionId?: number;
    rankId?: number;
    isLeader: boolean;
    job: number;
    state: number;
    respawnTime: number;
    drugAddiction: number;
    /**
     * The walking style of the character
     */
    walkingStyle: number;
    /**
     * The fighting style of the character
     */
    fightingStyle: number;
    createdAt: Date;
}
export namespace Character {
    export type GenderEnum = '0' | '1';
    export const GenderEnum = {
        _0: '0' as GenderEnum,
        _1: '1' as GenderEnum
    };
}