/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CharacterCreate { 
    accountId: number;
    name: string;
    birthday: string;
    gender: CharacterCreate.GenderEnum;
}
export namespace CharacterCreate {
    export type GenderEnum = '0' | '1';
    export const GenderEnum = {
        _0: '0' as GenderEnum,
        _1: '1' as GenderEnum
    };
}