/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Faction { 
    /**
     * The unique identifier of the faction.
     */
    id: number;
    /**
     * The name of the faction.
     */
    name: string;
    /**
     * The short name of the faction.
     */
    shortName: string;
    /**
     * The type of the faction.
     */
    type: number;
    /**
     * The X coordinate of the faction's position.
     */
    positionX: number;
    /**
     * The Y coordinate of the faction's position.
     */
    positionY: number;
    /**
     * The Z coordinate of the faction's position.
     */
    positionZ: number;
    /**
     * The virtual world identifier of the faction.
     */
    virtualWorld: number;
    /**
     * The interior identifier of the faction.
     */
    interior: number;
    /**
     * The budget of the faction.
     */
    budget: number;
}