/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PropertyType = 'HOUSE' | 'BUSINESS' | 'APARTMENT' | 'WAREHOUSE' | 'GARAGE';

export const PropertyType = {
    HOUSE: 'HOUSE' as PropertyType,
    BUSINESS: 'BUSINESS' as PropertyType,
    APARTMENT: 'APARTMENT' as PropertyType,
    WAREHOUSE: 'WAREHOUSE' as PropertyType,
    GARAGE: 'GARAGE' as PropertyType
};