/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';

export interface Property { 
    id?: number;
    type?: Property.TypeEnum;
    name: string;
    owner?: Character;
    price: number;
    address?: string;
    positionX: number;
    positionY: number;
    positionZ: number;
    exteriorVirtualWorld: number;
    exterior: number;
    interiorPositionX: number;
    interiorPositionY: number;
    interiorPositionZ: number;
    interior: number;
    isLocked?: boolean;
}
export namespace Property {
    export type TypeEnum = 'HOUSE' | 'BUSINESS' | 'APARTMENT' | 'WAREHOUSE';
    export const TypeEnum = {
        HOUSE: 'HOUSE' as TypeEnum,
        BUSINESS: 'BUSINESS' as TypeEnum,
        APARTMENT: 'APARTMENT' as TypeEnum,
        WAREHOUSE: 'WAREHOUSE' as TypeEnum
    };
}