/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BizType } from './bizType';
import { PropertyType } from './propertyType';

export interface Property { 
    id?: number;
    type?: PropertyType;
    bizType?: BizType;
    name: string;
    owner?: string;
    price: number;
    address?: string;
    positionX: number;
    positionY: number;
    positionZ: number;
    exteriorVirtualWorld: number;
    exterior: number;
    interiorPositionX: number;
    interiorPositionY: number;
    interiorPositionZ: number;
    interior: number;
    isLocked: boolean;
}