/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PropertyUpdate { 
    name?: string;
    price?: number;
    address?: string;
    positionX?: number;
    positionY?: number;
    positionZ?: number;
    exteriorVirtualWorld?: number;
    exterior?: number;
    interiorPositionX?: number;
    interiorPositionY?: number;
    interiorPositionZ?: number;
    interior?: number;
    isLocked?: boolean;
}