/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QuestionAnswer } from './questionAnswer';

export interface Question { 
    id: string;
    question: string;
    answers: Array<QuestionAnswer>;
}