/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VehicleUpdate { 
    positionX?: number;
    positionY?: number;
    positionZ?: number;
    rotation?: number;
    parkPositionX?: number;
    parkPositionY?: number;
    parkPositionZ?: number;
    parkRotation?: number;
    /**
     * Primary color code
     */
    primaryColor?: number;
    /**
     * Secondary color code
     */
    secondaryColor?: number;
}