/**
 * County RP API
 * API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';

export interface Vehicle { 
    id?: number;
    /**
     * Model ID of the vehicle
     */
    model: number;
    numberplate: string;
    owner?: Character;
    positionX?: number;
    positionY?: number;
    positionZ?: number;
    rotation?: number;
    price: number;
    parkPositionX?: number;
    parkPositionY?: number;
    parkPositionZ?: number;
    parkRotation?: number;
    /**
     * Primary color code
     */
    primaryColor?: number;
    /**
     * Secondary color code
     */
    secondaryColor?: number;
}